version: "3"
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "23306:3306"
